MGDOBR-816: Add Data Plane dependencies installation scripts
5733d9e2be6485d52ffa08870cabdee0/sandbox pull request #1134
Opened 2022-09-12 14:48 UTC by winklerm

[MGDOBR-816](https://issues.redhat.com/browse/MGDOBR-816)

<details>
<summary>
How to trigger pipelines and use the bots:
</summary>

- <b>Run the end to end pipeline</b>  
  Annotate the pull request with the label: `safe to test`. If you want to run the pipeline again, remove and add it again.

- <b>Rebase the pull request</b>  
  Comment with: `/rebase`.
- <b>Deploy BOT</b>
  Comment with `/deploy <dev,stable> when the PR has been merged to deploy to a target environment.

</details>

2022-09-14 15:32 UTC, msmagnanijr requested changes

2022-09-14 15:32 UTC, msmagnanijr commented on scripts/dependencies/servicemesh/kialiSub.yaml
> +  installPlanApproval: Manual
Please add:  startingCSV: kiali-operator.v1.48.2

2022-09-14 15:32 UTC, msmagnanijr commented on scripts/dependencies/servicemesh/serviceMeshSub.yaml
> +  installPlanApproval: Manual
Please add:   startingCSV: servicemeshoperator.v2.2.2

2022-09-14 15:32 UTC, msmagnanijr commented on scripts/dependencies/servicemesh/tracingSub.yaml
> +  installPlanApproval: Manual
Please add:   startingCSV: jaeger-operator.v1.36.0-2

2022-09-14 15:40 UTC, winklerm commented on scripts/dependencies/servicemesh/kialiSub.yaml
> +  installPlanApproval: Manual
Sure, good point!

2022-09-14 15:44 UTC, winklerm commented on scripts/dependencies/servicemesh/serviceMeshSub.yaml
> +  installPlanApproval: Manual
Done!

2022-09-14 15:44 UTC, winklerm commented on scripts/dependencies/servicemesh/kialiSub.yaml
> +  installPlanApproval: Manual
Done!

2022-09-14 15:46 UTC, winklerm commented
I have just realized that the Manual `installPlanApproval` needs to be approved (as described in [1]), will add it.

[1] https://olm.operatorframework.io/docs/tasks/install-operator-with-olm/

2022-09-15 14:08 UTC, winklerm commented on scripts/dependencies/install_dependencies.sh
> +oc apply -k servicemesh
Indeed, we have agreed with @vaibhavjainwiz to put those scripts in this PR until his change is ready - but it seems it was already merged 2 days ago. Please let me know if I should remove it, thanks!

2022-09-15 14:19 UTC, vaibhavjainwiz commented on scripts/dependencies/install_dependencies.sh
> +oc apply -k servicemesh
Hi @winklerm 
We could remove istio related script now. It is handled by operator now.

2022-09-15 14:28 UTC, winklerm commented on scripts/dependencies/install_dependencies.sh
> +oc apply -k servicemesh
Great, will remove it! One question, are all the resources in servicemesh/resources [1] handled by the operator (incl. the `istio-system` namespace creation)?

[1] https://github.com/5733d9e2be6485d52ffa08870cabdee0/sandbox/pull/1134/files#diff-86f35a740dda1558c43e4322904f4762f1b22f474a01d991b1db30ba66afba23

2022-09-15 14:33 UTC, winklerm commented on scripts/dependencies/install_dependencies.sh
> +oc apply -k servicemesh
Removed the service mesh resources, except for `istio-system` namespace, servicemesh control plane and service mesh member roll.

2022-09-15 18:11 UTC, msmagnanijr approved these changes
/lgtm

2022-09-15 18:17 UTC, winklerm commented
Added the plan approval and uninstallation script, tested against our OSD cluster, console output is here [1].

[1] http://pastebin.test.redhat.com/1073877

2022-09-21 09:31 UTC, vaibhavjainwiz approved these changes
lgtm

2022-09-21 09:34 UTC, merged