[MGDOBR-163] Adding Pormetheus ServiceMonitor to BridgeExecutor
5733d9e2be6485d52ffa08870cabdee0/sandbox pull request #184
Opened 2021-12-15 15:07 UTC by ricardozanini

Signed-off-by: Ricardo Zanini <zanini@redhat.com>

[MGDOBR-163](https://issues.redhat.com/browse/MGDOBR-163) 

Small change to `BridgeExecutor` to include `ServiceMonitor`. If Prometheus is not available, the CR will change its status to `Ready: false` and will notify the manager, so the component status will be `FAILED`.

I tried to do a small refactoring of the Controllers since they have almost the same algorithm. It's fairly easy to do, but the change would be huge. I'd rather have it in another PR. @r00ta @robpblake wdyt? I can open a JIRA to make the `ShardController` and `ShardResource` to manage the common bits between these two.

Please make sure that your PR meets the following requirements:

- [x] Your code is properly formatted according to [this configuration](https://github.com/kiegroup/kogito-runtimes/tree/main/kogito-build/kogito-ide-config)
- [x] Your commit messages are clear and reference the JIRA issue e.g: "[MGDOBR-1] - $clear_explanation_of_what_you_did"
- [x] All new functionality is tested
- [x] Pull Request title is properly formatted: `MGDOBR-XYZ Subject`
- [x] Pull Request contains link to the JIRA issue
- [x] Pull Request contains link to any dependent or related Pull Request
- [x] Pull Request contains description of the issue
- [x] Pull Request does not include fixes for issues other than the main ticket

2021-12-15 15:42 UTC, r00ta requested changes
Hey @ricardozanini , you are missing to set the `app.kubernetes.io/component: ` label on the ServiceMonitor CRD. If you don't set it, the controller does not get called when the resource is updated

2021-12-15 15:42 UTC, r00ta commented on shard-operator/src/main/java/com/redhat/service/bridge/shard/operator/controllers/BridgeExecutorController.java
> +            bridgeExecutor.getStatus().markConditionFalse(ConditionType.Ready, ConditionReason.PrometheusUnavailable, ConditionMessages.PROMETHEUS_UNVAILABLE);
I'd also add a `LOGGER.warn` since the deployment failed due to our internal misconfiguration

2021-12-15 16:02 UTC, sutaakar approved these changes

2021-12-15 17:01 UTC, ricardozanini commented
> Hey @ricardozanini , you are missing to set the `app.kubernetes.io/component: ` label on the ServiceMonitor CRD. If you don't set it, the controllers do not get called when the resource is updated

Indeed!

I've updated the PR. Please I need the reply about the refactoring of these controllers.

2021-12-16 09:24 UTC, r00ta approved these changes
Thanks @ricardozanini . 

Regarding the refactoring of the Controllers, I have some doubts honestly. They are _similar_ because they both provision a Deployment and a Service. But
1) We still need to register 2 controllers
2) The Deployment and the Service are configured differently
3) The BridgeController deploys a Route then

I don't know if the code is going to improve just to remove the apparent duplication of the management of the Deployment/Service (literally 10 lines of code). At the moment the two controllers are pretty separated, and I think it's a good thing for different reasons at the end.

But maybe I'm not getting what you have in mind, so if you have a clear picture of the refactoring of the components a diagram or a schema would help me.

2021-12-16 09:28 UTC, r00ta commented
> Thanks @ricardozanini .
> 
> Regarding the refactoring of the Controllers, I have some doubts honestly. They are _similar_ because they both provision a Deployment and a Service. But
> 
> 1. We still need to register 2 controllers
> 2. The Deployment and the Service are configured differently
> 3. The BridgeController deploys a Route then
> 
> I don't know if the code is going to improve just to remove the apparent duplication of the management of the Deployment/Service (literally 10 lines of code). At the moment the two controllers are pretty separated, and I think it's a good thing for different reasons at the end.
> 
> But maybe I'm not getting what you have in mind, so if you have a clear picture of the refactoring of the components a diagram or a schema would help me.

Thinking about it again.. maybe you are thinking about something like a `public abstract class BridgeIngressController<T extends CustomResource> implements ResourceController<T>` and put there some utility methods like `isDeploymentReady` and some others to be overwritten by the concrete Controllers?

2021-12-16 09:32 UTC, merged

2021-12-16 11:46 UTC, ricardozanini commented
> Thinking about it again.. maybe you are thinking about something like a public abstract class BridgeIngressController<T extends CustomResource> implements ResourceController<T> and put there some utility methods like isDeploymentReady and some others to be overwritten by the concrete Controllers?

Something like that. They will share the use cases, but we will keep them separatedely. There's a lot of opportunities to use some patterns to improve reuse.