MGDOBR-312 Creating a SlackAction without parameters gives an Internal server error
5733d9e2be6485d52ffa08870cabdee0/sandbox pull request #393
Opened 2022-03-02 14:52 UTC by lucamolteni

[Creating a SlackAction without parameters gives an Internal server error](https://issues.redhat.com/browse/MGDOBR-312) 

Please make sure that your PR meets the following requirements:

- [ ] Your code is properly formatted according to [this configuration](https://github.com/kiegroup/kogito-runtimes/tree/main/kogito-build/kogito-ide-config)
- [ ] Your commit messages are clear and reference the JIRA issue e.g: "[MGDOBR-1] - $clear_explanation_of_what_you_did"
- [ ] All new functionality is tested
- [ ] Pull Request title is properly formatted: `MGDOBR-XYZ Subject`
- [ ] Pull Request contains link to the JIRA issue
- [ ] Pull Request contains link to any dependent or related Pull Request
- [ ] Pull Request contains description of the issue
- [ ] Pull Request does not include fixes for issues other than the main ticket

<details>
<summary>
How to trigger pipelines and use the bots:
</summary>

* <b>Run the end to end pipeline</b>  
  Annotate the pull request with the label: `safe to test`. If you want to run the pipeline again, remove and add it again.

* <b>Rebase the pull request</b>  
  Comment with: `/rebase`.

</details>

2022-03-02 15:50 UTC, sutaakar approved these changes

2022-03-02 16:29 UTC, sutaakar commented
@lucamolteni thinking whether we should revisit also error messages for other actions.

2022-03-03 08:11 UTC, r00ta requested changes

2022-03-03 08:11 UTC, r00ta commented on manager/src/main/java/com/redhat/service/bridge/manager/actions/connectors/SlackActionValidator.java
> +            String.format("Missing 'parameter' field with the following parameters: %s,%s", SlackAction.CHANNEL_PARAMETER, SlackAction.WEBHOOK_URL_PARAMETER);
```suggestion
            String.format("Missing 'parameters' field with the following parameters: %s,%s", SlackAction.CHANNEL_PARAMETER, SlackAction.WEBHOOK_URL_PARAMETER);
```

2022-03-03 08:13 UTC, r00ta commented
Do we have a ticket to fix all the other actions? If you try to create any other action without the `parameters` attribute you are going to face the same problem

2022-03-03 15:53 UTC, lucamolteni commented
@r00ta @sutaakar by putting @Valid on the `BaseAction` we don't need to specify the validation on each kind of request, WDYT?

2022-03-04 08:36 UTC, r00ta approved these changes

2022-03-04 14:24 UTC, sutaakar approved these changes

2022-03-04 14:25 UTC, merged