Rename OPENSHIFT_OFFLINE_TOKEN to MANAGED_CONNECTORS_AUTH_OFFLINE_TOKEN
5733d9e2be6485d52ffa08870cabdee0/sandbox pull request #692
Opened 2022-04-28 14:28 UTC by lucamolteni

NO-JIRA

## PR owner checklist

Please make sure that your PR meets the following requirements:

- [ ] Your code is properly formatted according to [this configuration](https://github.com/kiegroup/kogito-runtimes/tree/main/kogito-build/kogito-ide-config).  
  *Run `mvn clean verify -DskipTests` so that imports are correctly set.*
- [ ] Your commit messages are clear and reference the JIRA issue e.g: "[MGDOBR-1] - $clear_explanation_of_what_you_did"
- [ ] All new functionality is tested
- [ ] Pull Request title is properly formatted: `MGDOBR-XYZ Subject`
- [ ] Pull Request contains link to the JIRA issue
- [ ] Pull Request contains link to any dependent or related Pull Request
- [ ] Pull Request contains description of the issue
- [ ] Pull Request does not include fixes for issues other than the main ticket

## PR reviewer(s) checklist

- [ ] Check if code and Github action workflows have been modified and if the modification is safe
- [ ] If the modification is safe, add the `safe to test` label

<details>
<summary>
How to trigger pipelines and use the bots:
</summary>

- <b>Run the end to end pipeline</b>  
  Annotate the pull request with the label: `safe to test`. If you want to run the pipeline again, remove and add it again.

- <b>Rebase the pull request</b>  
  Comment with: `/rebase`.

</details>

2022-04-28 14:50 UTC, manstis approved these changes

2022-04-28 14:50 UTC, manstis commented on dev/bin/manager-run.sh
> +# - MANAGED_CONNECTORS_AUTH_OFFLINE_TOKEN: Red Hat account offline token used by the fleet manager to authenticate to manage connectors (required)
If I wanted to be really pedantic I'd suggest this should be "... to manage**d** connectors..."

2022-04-28 15:36 UTC, robpblake approved these changes
@lucamolteni Looks fine to me. I know it's a pain, but can you please create a JIRA for this otherwise we loose visibility on these small tasks that take up our time.

Can you also please update the environment spreadsheet to match the rename as well please to avoid any more confusion.

cheers,

Rob

2022-04-29 06:48 UTC, r00ta requested changes
I think you missed to update `dev/README.md` and `startMinikubeDeployLocalDev.sh`

2022-04-29 12:56 UTC, lucamolteni commented
I forgot this one as well  (has to be done when it's merged)
https://docs.google.com/spreadsheets/d/1Ud8BnqJJs6O0nZtD8o4WIFTqExcrfvofjCqWqJtX8YI/edit#gid=0

2022-05-02 14:17 UTC, lucamolteni commented
> @lucamolteni Looks fine to me. I know it's a pain, but can you please create a JIRA for this otherwise we loose visibility on these small tasks that take up our time.

https://issues.redhat.com/browse/MGDOBR-672

2022-05-02 14:46 UTC, sutaakar approved these changes

2022-05-02 14:56 UTC, r00ta approved these changes

2022-05-02 14:57 UTC, merged