MGDOBR-658: Add bridges filtering support
5733d9e2be6485d52ffa08870cabdee0/sandbox pull request #752
Opened 2022-05-12 12:46 UTC by manstis

[https://issues.redhat.com/browse/MGDOBR-658](https://issues.redhat.com/browse/MGDOBR-658)

This is a duplication of #741 but hopefully this will get a proper SonarCloud analysis.

## PR owner checklist

Please make sure that your PR meets the following requirements:

- [x] Your code is properly formatted according to [this configuration](https://github.com/kiegroup/kogito-runtimes/tree/main/kogito-build/kogito-ide-config).  
  *Run `mvn clean verify -DskipTests` so that imports are correctly set.*
- [x] Your commit messages are clear and reference the JIRA issue e.g: "[MGDOBR-1] - $clear_explanation_of_what_you_did"
- [x ] The layers in the `kustomize` folder have been updated accordingly.
- [x] All new functionality is tested
- [x] Pull Request title is properly formatted: `MGDOBR-XYZ Subject`
- [x] Pull Request contains link to the JIRA issue
- [x] Pull Request contains link to any dependent or related Pull Request
- [x] Pull Request contains description of the issue
- [x] Pull Request does not include fixes for issues other than the main ticket

## PR reviewer(s) checklist

- [ ] Check if code and Github action workflows have been modified and if the modification is safe
- [ ] If the modification is safe, add the `safe to test` label

<details>
<summary>
How to trigger pipelines and use the bots:
</summary>

- <b>Run the end to end pipeline</b>  
  Annotate the pull request with the label: `safe to test`. If you want to run the pipeline again, remove and add it again.

- <b>Rebase the pull request</b>  
  Comment with: `/rebase`.
- <b>Deploy BOT</b>
  Comment with `/deploy <dev,stable> when the PR has been merged to deploy to a target environment.

</details>

2022-05-12 13:14 UTC, manstis commented
@jomarko @danielezonca I am at a loss now.

This PR contains a single commit and was created after (and includes) the GHA workflow change for `fetch-depth: 0`.

SonarCloud still steadfastly refuses to see the [unit tests](https://github.com/5733d9e2be6485d52ffa08870cabdee0/sandbox/pull/752/files#diff-23819953a92802e4d712ad1b898ab58b1080b6516ccab28f16c513a3c86571b6R113-R209).

2022-05-12 14:53 UTC, lucamolteni requested changes

2022-05-12 14:53 UTC, lucamolteni commented on manager/src/main/java/com/redhat/service/smartevents/manager/dao/BridgeDAO.java
> +    private static final int FILTER_NAME = 1;
`FILTER_BY_NAME`

2022-05-12 14:59 UTC, manstis commented on manager/src/main/java/com/redhat/service/smartevents/manager/dao/BridgeDAO.java
> +        int query = 0;
Done.

2022-05-12 14:59 UTC, manstis commented on manager/src/main/java/com/redhat/service/smartevents/manager/dao/BridgeDAO.java
> +    private static final int FILTER_NAME = 1;
Done.

2022-05-12 14:59 UTC, manstis commented on manager/src/main/java/com/redhat/service/smartevents/manager/dao/BridgeDAO.java
> +    private static final int FILTER_STATUS = 2;
Done.

2022-05-12 15:01 UTC, manstis commented on manager/src/main/java/com/redhat/service/smartevents/manager/dao/BridgeDAO.java
> +                total = find("#BRIDGE.findByCustomerId", parameters).count();
@lucamolteni Thank-you for the pointer. I investigated Panache as you proposed and it actually rewrites the `SELECT ... FROM ...` statement into a `SELECT COUNT(*) FROM ...` statement in `io.quarkus.panache.hibernate.common.runtime.PanacheJpaUtil#getCountQuery(..)` called from the `count()` method. Therefore this is actually as efficient as I could hand-craft with additional queries.

2022-05-12 15:18 UTC, manstis commented on manager/src/main/java/com/redhat/service/smartevents/manager/dao/BridgeDAO.java
> +                total = find("#BRIDGE.findByCustomerId", parameters).count();
I'll have a look at Hibernate Filters though, which could improve the whole situation too.

I didn't know such a thing existed to be honest but whilst looking through the Panache code I found them.

2022-05-13 10:27 UTC, manstis commented on manager/src/main/java/com/redhat/service/smartevents/manager/dao/BridgeDAO.java
> +                total = find("#BRIDGE.findByCustomerId", parameters).count();
@lucamolteni Filtering has been completely refactored and looks much better for it :dancing_women:

2022-05-13 10:27 UTC, manstis commented
@jomarko @lucamolteni @Srihari1192 This PR has been refactored to leverage Hibernate better for filtering.

Please feel free to re-review.

2022-05-13 10:28 UTC, manstis commented on manager/src/main/java/com/redhat/service/smartevents/manager/dao/BridgeDAO.java
> +        String filterName = queryInfo.getFilterInfo().getFilterName();
Look how pretty the new filtering code is!

2022-05-13 10:29 UTC, manstis commented on manager/src/main/java/com/redhat/service/smartevents/manager/dao/EnumTypeManagedResourceStatus.java
> +public class EnumTypeManagedResourceStatus extends EnumType<ManagedResourceStatus> {
Look how less pretty this hack-around is.. but I think it's a worthy alternative.

Without this we need to convert the `ManagedResourceStatus` enum values to `String` to use in the `FilterDef`.

2022-05-13 10:30 UTC, manstis commented on manager/src/main/java/com/redhat/service/smartevents/manager/dao/BridgeDAO.java
> +            query.filter("byStatus", Parameters.with("status", filterStatus));
Without the hackery magic (see below) I'd need to convert the statuses to `String`.

2022-05-16 08:24 UTC, kelvah approved these changes

2022-05-16 11:37 UTC, Srihari1192 approved these changes

2022-05-16 14:59 UTC, manstis commented
@jomarko @r00ta Could you please review (or say you don't want to/feel the need to).

2022-05-16 15:26 UTC, sutaakar commented
Jozef is on PTO, removing him from reviewers

2022-05-17 13:49 UTC, lucamolteni approved these changes

2022-05-17 13:59 UTC, merged